# Generated by Django 5.2.5 on 2025-09-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_product_images_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Images',
            new_name='Flower_Images',
        ),
    ]
