# Generated by Django 5.2.5 on 2025-09-02 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_rename_product_images_flower_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='flowers.category'),
        ),
    ]
