# Generated by Django 5.2.5 on 2025-09-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart_items',
            unique_together={('cart', 'flower')},
        ),
    ]
